package com.tenmilelabs.tools.themealdb

import java.time.Instant

/**
 * Renders a [MappingResult] as a single idempotent SQL file, applied the same way as the
 * existing seed scripts:
 *
 * ```
 * psql -h localhost -U postgres -d chefai_db -f src/main/resources/sql/seed_themealdb.sql
 * ```
 *
 * Every statement uses `ON CONFLICT ... DO NOTHING` — unlike the first half of `seed.sql`, this
 * file is safe to apply more than once. Write order respects FKs: creator user, then new
 * ingredient/tag/label catalog rows, then recipes, then everything that references a recipe.
 *
 * Note `DO NOTHING`, not `DO UPDATE`: re-running the importer and re-applying its output will
 * *not* refresh a recipe whose upstream TheMealDB content changed since the first import — the
 * original row wins silently because its UUID is deterministic and the conflicting insert is
 * simply skipped.
 */
object SeedSqlWriter {
    fun write(result: MappingResult, importedAtMillis: Long): String = buildString {
        appendLine("-- Generated by `./gradlew importTheMealDb` — do not hand-edit, regenerate instead.")
        appendLine("-- Source: TheMealDB (https://www.themealdb.com/api.php), a free, explicitly reusable")
        appendLine("-- recipe API (not scraped content). Attribution is carried per-recipe in")
        appendLine("-- recipe_external_url. See docs/meal-plan-roadmap.md (Phase 1) for the sourcing rationale.")
        appendLine("--")
        appendLine("-- prep_time_minutes / cook_time_minutes / servings are HEURISTIC ESTIMATES, not sourced")
        appendLine("-- facts — TheMealDB provides none of the three. See")
        appendLine("-- TheMealDbMapper.estimateTimingsAndServings for the derivation.")
        appendLine("--")
        appendLine("-- Generated at: ${Instant.ofEpochMilli(importedAtMillis)}")
        appendLine("-- Idempotent: every statement below is conflict-safe, so re-running this file is a no-op.")
        appendLine("-- Apply after seed.sql: psql ... -f seed.sql -f seed_themealdb.sql")
        appendLine()

        writePreflightGuard(this)

        writeSystemUser(this)
        writeCatalogRows(this, "ingredients", result.newIngredients.map { it.id to it.displayName }, importedAtMillis)
        writeCatalogRows(this, "tags", result.newTags.map { it.id to it.displayName }, importedAtMillis)
        writeCatalogRows(this, "labels", result.newLabels.map { it.id to it.displayName }, importedAtMillis)
        writeRecipes(this, result.recipes)
        writeRecipeSteps(this, result.recipes)
        writeRecipeIngredients(this, result.recipes, importedAtMillis)
        writeRecipeTags(this, result.recipes, importedAtMillis)
        writeRecipeLabels(this, result.recipes, importedAtMillis)
    }

    /**
     * Fails loudly when `seed.sql` has not been applied first.
     *
     * Every junction INSERT below is one multi-row statement referencing curated catalog UUIDs, so
     * against a bare schema each one aborts *in its entirety* on the first FK violation — leaving
     * every recipe with no tags, no labels and no ingredients. Without `ON_ERROR_STOP`, psql prints
     * three ERROR lines, exits 0, and the import looks like it worked. That is exactly how the
     * database behind jmuci/ChefAI#182 ended up with 789 ingredient-less recipes.
     *
     * `\set ON_ERROR_STOP on` is a psql client directive, harmless to any tool that only reads the
     * SQL statements; the DO block is the real guard and works through any client.
     */
    private fun writePreflightGuard(sb: StringBuilder) {
        sb.appendLine("-- ===============================")
        sb.appendLine("-- PREFLIGHT: seed.sql must already be applied")
        sb.appendLine("-- ===============================")
        sb.appendLine("\\set ON_ERROR_STOP on")
        sb.appendLine("DO $$")
        sb.appendLine("BEGIN")
        sb.appendLine("  IF NOT EXISTS (SELECT 1 FROM tags WHERE uuid = '50000000-0000-0000-0000-000000000008') THEN")
        sb.appendLine("    RAISE EXCEPTION 'seed.sql must be applied before seed_themealdb.sql: the curated "  +
            "catalog (tags/labels/ingredients) is missing, and every junction INSERT in this file would "  +
            "abort on a foreign-key violation, silently leaving recipes with no tags or ingredients.';")
        sb.appendLine("  END IF;")
        sb.appendLine("END $$;")
        sb.appendLine()
    }

    private fun writeSystemUser(sb: StringBuilder) {
        sb.appendLine("-- ===============================")
        sb.appendLine("-- SYSTEM CREATOR USER (TheMealDB import)")
        sb.appendLine("-- ===============================")
        sb.appendLine(
            "INSERT INTO users (uuid, user_name, display_name, email, password_hash, avatar_url, created_at, updated_at) VALUES"
        )
        sb.appendLine(
            "  ('${TheMealDbMapper.SYSTEM_CREATOR_ID}','themealdb','TheMealDB Import'," +
                "'${TheMealDbMapper.SYSTEM_CREATOR_EMAIL}','!','',now(),now())"
        )
        sb.appendLine("ON CONFLICT (uuid) DO NOTHING;")
        sb.appendLine()
    }

    private fun writeCatalogRows(sb: StringBuilder, table: String, rows: List<Pair<java.util.UUID, String>>, importedAtMillis: Long) {
        if (rows.isEmpty()) return
        sb.appendLine("-- ===============================")
        sb.appendLine("-- NEW $table (from TheMealDB import)")
        sb.appendLine("-- ===============================")
        sb.appendLine("INSERT INTO $table (uuid, display_name, updated_at, deleted_at, server_updated_at) VALUES")
        sb.appendJoinedRows(rows) { (id, name) ->
            "('$id',${sqlString(name)},$importedAtMillis,NULL,now())"
        }
        sb.appendLine("ON CONFLICT (uuid) DO NOTHING;")
        sb.appendLine()
    }

    private fun writeRecipes(sb: StringBuilder, recipes: List<MappedRecipe>) {
        if (recipes.isEmpty()) return
        sb.appendLine("-- ===============================")
        sb.appendLine("-- RECIPES (TheMealDB import)")
        sb.appendLine("-- ===============================")
        sb.appendLine(
            "INSERT INTO recipes (uuid, title, description, image_url, image_url_thumbnail, " +
                "prep_time_minutes, cook_time_minutes, servings, creator_id, recipe_external_url, " +
                "privacy, updated_at, deleted_at, server_updated_at) VALUES"
        )
        sb.appendJoinedRows(recipes) { r ->
            "('${r.id}',${sqlString(r.title)},${sqlString(r.description)},${sqlString(r.imageUrl)}," +
                "${sqlString(r.imageUrlThumbnail)},${r.prepTimeMinutes},${r.cookTimeMinutes},${r.servings}," +
                "'${r.creatorId}',${sqlNullableString(r.recipeExternalUrl)},'PUBLIC',${r.updatedAtMillis},NULL,now())"
        }
        sb.appendLine("ON CONFLICT (uuid) DO NOTHING;")
        sb.appendLine()
    }

    private fun writeRecipeSteps(sb: StringBuilder, recipes: List<MappedRecipe>) {
        val rows = recipes.flatMap { r -> r.steps.map { r to it } }
        if (rows.isEmpty()) return
        sb.appendLine("-- ===============================")
        sb.appendLine("-- RECIPE STEPS (TheMealDB import)")
        sb.appendLine("-- ===============================")
        sb.appendLine("INSERT INTO recipe_steps (uuid, recipe_id, order_index, instruction, updated_at, deleted_at, server_updated_at) VALUES")
        sb.appendJoinedRows(rows) { (r, step) ->
            "('${step.id}','${r.id}',${step.orderIndex},${sqlString(step.instruction)},${r.updatedAtMillis},NULL,now())"
        }
        sb.appendLine("ON CONFLICT (uuid) DO NOTHING;")
        sb.appendLine()
    }

    private fun writeRecipeIngredients(sb: StringBuilder, recipes: List<MappedRecipe>, importedAtMillis: Long) {
        val rows = recipes.flatMap { r -> r.ingredients.map { r to it } }
        if (rows.isEmpty()) return
        sb.appendLine("-- ===============================")
        sb.appendLine("-- RECIPE INGREDIENTS (TheMealDB import)")
        sb.appendLine("-- ===============================")
        sb.appendLine("INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit, updated_at, deleted_at, server_updated_at) VALUES")
        sb.appendJoinedRows(rows) { (r, ing) ->
            "('${r.id}','${ing.ingredientId}',${ing.quantity},${sqlString(ing.unit)},${r.updatedAtMillis},NULL,now())"
        }
        sb.appendLine("ON CONFLICT (recipe_id, ingredient_id) DO NOTHING;")
        sb.appendLine()
    }

    private fun writeRecipeTags(sb: StringBuilder, recipes: List<MappedRecipe>, importedAtMillis: Long) {
        val rows = recipes.flatMap { r -> r.tagIds.map { r to it } }
        if (rows.isEmpty()) return
        sb.appendLine("-- ===============================")
        sb.appendLine("-- RECIPE TAGS (TheMealDB import)")
        sb.appendLine("-- ===============================")
        sb.appendLine("INSERT INTO recipe_tags (recipe_id, tag_id, updated_at, deleted_at, server_updated_at) VALUES")
        sb.appendJoinedRows(rows) { (r, tagId) -> "('${r.id}','$tagId',${r.updatedAtMillis},NULL,now())" }
        sb.appendLine("ON CONFLICT (recipe_id, tag_id) DO NOTHING;")
        sb.appendLine()
    }

    private fun writeRecipeLabels(sb: StringBuilder, recipes: List<MappedRecipe>, importedAtMillis: Long) {
        val rows = recipes.flatMap { r -> r.labelIds.map { r to it } }
        if (rows.isEmpty()) return
        sb.appendLine("-- ===============================")
        sb.appendLine("-- RECIPE LABELS (TheMealDB import)")
        sb.appendLine("-- ===============================")
        sb.appendLine("INSERT INTO recipe_labels (recipe_id, label_id, updated_at, deleted_at, server_updated_at) VALUES")
        sb.appendJoinedRows(rows) { (r, labelId) -> "('${r.id}','$labelId',${r.updatedAtMillis},NULL,now())" }
        sb.appendLine("ON CONFLICT (recipe_id, label_id) DO NOTHING;")
        sb.appendLine()
    }

    private fun <T> StringBuilder.appendJoinedRows(rows: List<T>, render: (T) -> String) {
        rows.forEachIndexed { index, row ->
            append("  ")
            append(render(row))
            appendLine(if (index == rows.lastIndex) "" else ",")
        }
    }

    private fun sqlString(s: String): String = "'${s.replace("'", "''")}'"
    private fun sqlNullableString(s: String?): String = if (s == null) "NULL" else sqlString(s)
}
